Final-Project-Eshop/src/main/java/com/finalproject/euromobil/site/entities/Goods.java
package com.finalproject.euromobil.site.entities;

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

@Entity
@Table(name="goods")
public class Goods {
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    @Column
    private String name;
    
    @ManyToOne
    @JoinColumn(name="brand_id", nullable=false)
    private Brand brand;
    
    @Column
    private String description;
    
    @Column
    private Long price;
    
    @Column
    private boolean isEnabled;
        
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="image_id", nullable=false)
    private Images images;    
    
    @ManyToMany
    @JoinTable(
        name = "goods_kategories", 
        joinColumns = @JoinColumn(name = "goods_id"), 
        inverseJoinColumns = @JoinColumn(name = "kategory_id"))
    private List<Kategory> kategories;

    public List<Kategory> getKetegories() {
        return kategories;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setBrand(Brand brand) {
        this.brand = brand;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setPrice(Long price) {
        this.price = price;
    }

    public void setIsEnabled(boolean isEnabled) {
        this.isEnabled = isEnabled;
    }

    public void setImages(Images images) {
        this.images = images;
    }

    public Long getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public Brand getBrand() {
        return brand;
    }

    public String getDescription() {
        return description;
    }

    public Long getPrice() {
        return price;
    }

    public boolean getIsEnabled() {
        return isEnabled;
    }

    public Images getImages() {
        return images;
    }

    public void setKategories(List<Kategory> kategories) {
        this.kategories = kategories;
    }    
}

Final-Project-Eshop/src/main/java/com/finalproject/euromobil/site/controllers/admin/GoodsController.java
package com.finalproject.euromobil.site.controllers.admin;

import com.finalproject.euromobil.site.entities.Brand;
import com.finalproject.euromobil.site.entities.Goods;
import com.finalproject.euromobil.site.exceptions.UnsupportedImageTypeException;
import com.finalproject.euromobil.site.forms.GoodsForm;
import com.finalproject.euromobil.site.forms.filterforms.GoodsFilterFrom;
import com.finalproject.euromobil.site.services.BrandService;
import com.finalproject.euromobil.site.services.GoodsService;
import com.finalproject.euromobil.site.services.KategoryService;
import java.io.IOException;
import java.util.List;
import java.util.Set;
import java.util.StringJoiner;
import javax.inject.Inject;
import javax.servlet.http.HttpSession;
import javax.validation.Valid;
import org.hibernate.exception.ConstraintViolationException;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.util.StringUtils;
import org.springframework.validation.BindingResult;
import org.springframework.validation.FieldError;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

@Controller
@RequestMapping("/admin/goods")
public class GoodsController 
{
    @Inject
    private GoodsService goodsService;
    
    @Inject
    private BrandService brandService;
    
    @Inject
    private KategoryService kategoryService;
    
    @GetMapping({"/", ""})
    public String goods(Model model, 
            Pageable pageable, 
            @RequestParam(required = false) String sort,
            @RequestParam(required = false) Set<Long> kategoryIds,
            @RequestParam(required = false) Set<Long> brandIds,
            @RequestParam(required = false) String search,
            HttpSession session)
            
    {
        boolean showResetButton =
                (kategoryIds != null && !kategoryIds.isEmpty())
                || !StringUtils.isEmpty(search)
                || !StringUtils.isEmpty(sort)
                || (brandIds != null && !brandIds.isEmpty());
        model.addAttribute("showResetButton", showResetButton);
        
        Page<Goods> page = goodsService.findFiltered(kategoryIds, brandIds, search, pageable, false);
        GoodsFilterFrom goodsFilterFrom = new GoodsFilterFrom();
        if(!StringUtils.isEmpty(sort))
        { 
            String[] sortDirection = sort.split(",");
            
            goodsFilterFrom.setSort(sortDirection[0]);
            goodsFilterFrom.setDirection(sortDirection[1]);
        }
        if(kategoryIds != null && !kategoryIds.isEmpty())
        {
            goodsFilterFrom.setKategory(kategoryIds);
            
            StringJoiner kategoryJoiner = new StringJoiner(",");
            kategoryIds.forEach(id -> {
                kategoryJoiner.add(id.toString());
            });
            model.addAttribute("kategoryIds", kategoryJoiner.toString());
        }
        else
        {
            model.addAttribute("kategoryIds", "");
        }
        if(brandIds != null && !brandIds.isEmpty())
        {
            goodsFilterFrom.setBrand(brandIds);
            
            StringJoiner brandJoiner = new StringJoiner(",");
            brandIds.forEach(id -> {
                brandJoiner.add(id.toString());
            });
            model.addAttribute("brandIds", brandJoiner.toString());
        }
        else
        {
            model.addAttribute("brandIds", "");
        }
        if(!StringUtils.isEmpty(search))
        {
            goodsFilterFrom.setSearch(search);
        }

        model.addAttribute("goodsFilterForm", goodsFilterFrom);
        model.addAttribute("kategories", kategoryService.findAll());
        model.addAttribute("page", page);
        model.addAttribute("brands", brandService.findAll());
             
        model.addAttribute("search", search);
        model.addAttribute("sort", page
                .getSort()
                .get()
                .map(s -> s.getProperty() + "," + s.getDirection().name().toLowerCase())
                .findFirst()
                .orElse(null));
        
        session.setAttribute("pageNum", pageable.getPageNumber());
        session.setAttribute("sort", sort);
        session.setAttribute("kategoryIds", kategoryIds);
        session.setAttribute("brandIds", brandIds);
        session.setAttribute("search", search);
        
        return "/goods/goods";
    }
    
    @PostMapping("")
    public String filterGoods(GoodsFilterFrom goodsFilterFrom, RedirectAttributes redirectAttributes)
    {
        String sort = goodsFilterFrom.getSort();
        String direction = goodsFilterFrom.getDirection();
        Set<Long> kategoryIds = goodsFilterFrom.getKategory();
        Set<Long> brandIds = goodsFilterFrom.getBrand();
        String search = goodsFilterFrom.getSearch();
        
        if(!StringUtils.isEmpty(sort))
        {
            redirectAttributes.addAttribute("sort", sort + "," + direction);
        }
        if(kategoryIds != null && !kategoryIds.isEmpty())
        {
            redirectAttributes.addAttribute("kategoryIds", kategoryIds);
        }
        if(brandIds != null && !brandIds.isEmpty())
        {
            redirectAttributes.addAttribute("brandIds", brandIds);
        }
        if(!StringUtils.isEmpty(search))
        {
            redirectAttributes.addAttribute("search", search);
        }
        
        return "redirect:/admin/goods";
    }
    
    @RequestMapping(value="/add-goods", method=RequestMethod.GET)
    public String addForm(Model model) 
    {
        GoodsForm goodsForm = new GoodsForm();        
        model.addAttribute("goodsForm", goodsForm);
        
        List<Brand> brands = brandService.findAll();
        model.addAttribute("brands", brands);
        
        return "/goods/add-goods";
    }
    
    @RequestMapping(value="/add-goods", method=RequestMethod.POST) 
    public String add(@Valid GoodsForm goodsForm, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpSession session) throws IOException
    {
        if (bindingResult.hasErrors())
        {
            model.addAttribute("brands", brandService.findAll());
            return "/goods/add-goods";
        }

        try
        {
            Goods goods = this.goodsService.create(goodsForm);
            redirectAttributes.addFlashAttribute("successMessage", "Produkt " + goods.getName() + " Byl úspěšně uložen");
        }
        catch(UnsupportedImageTypeException e)
        {
            model.addAttribute("brands", brandService.findAll());
            
            bindingResult.addError(new FieldError("goodsForm", "image", e.getMessage()));
            return "/goods/add-goods";
        }
        catch(Exception ex)
        {
            redirectAttributes.addFlashAttribute("errorMessage", "Produkt se nepodařilo přidat. Pravděpodobně už existuje");
        }
        
        redirectAttributes.addAttribute("page", session.getAttribute("pageNum"));
        redirectAttributes.addAttribute("sort", session.getAttribute("sort"));
        redirectAttributes.addAttribute("kategoryIds", session.getAttribute("kategoryIds"));
        redirectAttributes.addAttribute("brandIds", session.getAttribute("brandIds"));
        redirectAttributes.addAttribute("search", session.getAttribute("search"));
        
        return "redirect:/admin/goods";
    }
    
    @GetMapping("/edit-goods/{goodsId}")
    public String getEditGoods(@PathVariable long goodsId, Model model, RedirectAttributes redirectAttributes)
    { 
        if(!goodsService.findById(goodsId).isPresent())
        {
            redirectAttributes.addFlashAttribute("notFoundMessage", "Produkt s id " + goodsId + " neexistuje");
        }
        
        Goods g = goodsService.findById(goodsId).get();
        GoodsForm goodsForm = goodsService.fillForm(g);
        
        model.addAttribute("goodsForm", goodsForm);
        model.addAttribute("brands", brandService.findAll());
        model.addAttribute("goodsId", goodsId);
        
        return "/goods/edit-goods";
    }
    
    @PostMapping("/edit-goods/{goodsId}")
    public String editGoods(@Valid GoodsForm goodsForm, BindingResult bindingResult, @PathVariable long goodsId, Model model, RedirectAttributes redirectAttributes, HttpSession session) throws IOException
    {
        if (bindingResult.hasErrors())
        {
            model.addAttribute("brands", brandService.findAll());
            return "/goods/edit-goods";
        }

        try
        {
            Goods goods = goodsService.edit(goodsService.findById(goodsId).get(), goodsForm);
            
            redirectAttributes.addFlashAttribute("successMessage", "Produkt s id " + goodsId + " byl upraven");
        }
        catch(UnsupportedImageTypeException e)
        {
            model.addAttribute("brands", brandService.findAll());
            bindingResult.addError(new FieldError("goodsForm", "image", "Nepodporovaný typ obrázku"));
            return "/goods/edit-goods";
        }
        catch(Exception ex)
        {
            redirectAttributes.addFlashAttribute("errorMessage", "Produkt s id " + goodsId + " se nepodařilo upravit");  
        }
        
        redirectAttributes.addAttribute("page", session.getAttribute("pageNum"));
        redirectAttributes.addAttribute("sort", session.getAttribute("sort"));
        redirectAttributes.addAttribute("kategoryIds", session.getAttribute("kategoryIds"));

Final-Project-Eshop/src/main/webapp/WEB-INF/jsp/goods/add-goods.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
 <%@include file="/WEB-INF/jspf/base.jspf" %>
<c:set var="formTitle" value="Přidat zboží" />
<c:set var="formType" value="goodsForm"/>
<c:set var="formAction" value="add-goods"/>
<%@include file="/WEB-INF/jspf/goods-form.jspf" %>

Final-Project-Eshop/src/main/webapp/WEB-INF/jsp/goods/edit-goods.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
 <%@include file="/WEB-INF/jspf/base.jspf" %>
<c:set var="formTitle" value="Upravit zboží" />
<c:set var="formType" value="goodsForm"/>
<c:set var="formAction" value="${goodsId}"/>
<%@include file="/WEB-INF/jspf/goods-form.jspf" %>

Final-Project-Eshop/src/main/webapp/WEB-INF/jsp/goods/goods.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@include file="/WEB-INF/jspf/base.jspf" %>

<!DOCTYPE html>
<html lang="cs">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Zboží</title>

  <script src="/js/multiple-select-fix.js" charset="utf-8"></script> <%--prozatimní fix--%>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.js"></script>
  <script src="/js/materialize.js"></script>
  <script src="/js/myjs.js" charset="utf-8"></script>
  <script src="/js/forModal.js" charset="utf-8"></script>

  <link rel="stylesheet" href="/css/materialize.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="/css/vlastni-styly.css">
</head>
<body>
   <%@include file="/WEB-INF/jspf/modal-dialog.jspf" %>
   <c:set var="forAdmins" value="true" />
   <%@include file="/WEB-INF/jspf/navbar.jspf" %>

  <main>
    <div class="section">
      <div class="chip right">
        <img src="/img/user.png" alt="">
        <sec:authentication property="principal.username" />
      </div>
    </div>

    <div class="fixed-action-btn">
        <a href="goods/add-goods" class="btn-floating btn-large blue darken-4">
        <i class="large material-icons">add</i>
      </a>
    </div>

   <form:form method="post" action="/admin/goods" modelAttribute="goodsFilterForm">
    <div class="container">
      <div class="section">
        <div class="row grey lighten-2 valign-wrapper">
          <div class="input-field col s2">
            <form:select path="sort">
              <form:option value="" disabled="true" selected="selected">Řadit podle</form:option>
              <form:option value="price">cena</form:option>
              <form:option value="name">jméno</form:option>
              <form:option value="brand">značka</form:option>
            </form:select>
            <form:label path="sort">Řazení</form:label>
          </div>
          <div class="input-field col s2">
            <form:select path="direction">
              <form:option value="asc" selected="selected">Vzestupně</form:option>
              <form:option value="desc">Sestupně</form:option>
            </form:select>
          </div>
            <div class="input-field col s2 offset-s1">
              <form:select path="kategory" multiple="true">
                <form:option value="" disabled="true" selected="selected">kategorie</form:option>
                
                <c:forEach var="kategory" items="${kategories}">
                <form:option value="${kategory.id}">${kategory.name}</form:option>
                </c:forEach>
                
              </form:select>
                <form:label style="margin-bottom: 20px" path="kategory">Filtry</form:label>
            </div>
          
            <div class="input-field col s2">
              <form:select path="brand" multiple="multiple">
                <form:option value="" disabled="true" selected="selected">značky</form:option>
                
                <c:forEach items="${brands}" var="brand"> 
                
                <form:option value="${brand.id}">${brand.name}</form:option>
                                
                </c:forEach>
                
                
              </form:select>
            </div>
            <div class="input-field col s2">
              <form:input path="search" id="searchfield" type="text" class="validate"/>
              <form:label path="search" for="searchfield">název</form:label>
            </div>
            <div class="col s1 valign">
              <button class="blue darken-2 btn waves-effect waves-light" type="submit" name="action">
                <i class="material-icons center">search</i>
              </button>
                
            </div>
            <c:if test="${showResetButton}">
            <div class="col s1">
                <a class="btn blue darken-2" href="/admin/goods">RESET</a>
            </div>
            </c:if>
      </div>
    </div>
  </div>
  </form:form>
      
      <c:if test="${successMessage != null}">
            <%@include file="/WEB-INF/jspf/success-message.jspf" %>
        </c:if>
      
      <c:if test="${errorMessage != null}">
            <%@include file="/WEB-INF/jspf/error-message.jspf" %>
        </c:if>
      
      <c:if test="${notFoundMessage != null}">
            <%@include file="/WEB-INF/jspf/not-found-message.jspf" %>
        </c:if>

    <div class="container">
      <div class="section">
        <div class="row grey lighten-2">
          <div class="col s8 offset-s2">
              <c:if test="${showResetButton && page.isEmpty()}">
                <c:set var="notFoundMessage" value="pro tento výběr nebylo nic nalezeno" />
                <%@include file="/WEB-INF/jspf/not-found-message.jspf" %>
              </c:if>
              
            <ul class="collection">
                
             <c:forEach items="${page.getContent()}" var="goods">   
                
              <li class="collection-item avatar">
                <img src="/image/${goods.id}" alt="" class="circle">
                <span class="title text-bold">${goods.name}</span>
                <p>Cena: ${goods.price} Kč<br>
                   Značka: ${goods.brand.getName()}<br>
                                     
                   <c:forEach items="${goods.ketegories}" var="kategory">
                       ${kategory.name} 
                   </c:forEach>
                   
                </p>
                <a href="goods/edit-goods/${goods.id}" class="secondary-content blue-text text-darken-2 col-mar-30top col-mar-140right">Upravit</a>
                <a href="#confirmation" 
                   class="modal-trigger secondary-content blue-text text-darken-2 col-mar-30top col-mar-100right"
                   data-modal-title="Odstranit produkt"
                   data-modal-body="Opravdu chcete odstranit produkt ${goods.name}?"
                   data-modal-success-title="Odstranit"
                   data-modal-success-class="red"
                   data-modal-redirect="/admin/goods/delete-goods/${goods.id}">
                   <i class="material-icons">delete</i>
                </a>
                <a href="goods/enable-goods/${goods.id}" class="secondary-content ${goods.isEnabled == true ? 'green-text' : 'red-text'} col-mar-30top">${goods.isEnabled == true ? 'Aktivní' : 'Neaktivní'}</a>
              </li>
              
             </c:forEach> 

              
            </ul>
          </div>
        </div>
      </div>
    </div>
      
      <c:if test="${goods.pageable.pageNumber - 1 > page.totalPages}">
        <c:set var="notFoundMessage" value="Strana ${goods.pageable.pageNumber} neexistuje" />
        <%@include file="/WEB-INF/jspf/not-found-message.jspf" %>
    </c:if>
  <c:if test="${page.totalPages > 1}">    
  <div class="section">
    <div class="row">
      <div class="col s8 offset-s2">
        <ul class="pagination center">
            <li class="${page.isFirst() ? "disabled" : ""}"><a<c:if test="${!page.isFirst()}"> href="?page=${page.previousOrFirstPageable().pageNumber}&sort=${sort}&kategoryIds=${brandIds}&brandIds=${brandIds}&search=${search}"</c:if>><i class="material-icons">chevron_left</i></a></li>
          <c:forEach begin="1" end="${page.totalPages}" varStatus="pageIter">
          <li class="waves-effect ${page.pageable.pageNumber == pageIter.index - 1 ? "active blue darken-2" : ""}"><a href="?page=${pageIter.index - 1}&sort=${sort}&kategoryIds=${kategoryIds}&brandIds=${brandIds}&search=${search}">${pageIter.index}</a></li>
          </c:forEach>
          <li class="${page.isLast() ? "disabled" : ""}"><a<c:if test="${!page.isLast()}"> href="?page=${page.nextOrLastPageable().pageNumber}&sort=${sort}&kategoryIds=${kategoryIds}&brandIds=${brandIds}&search=${search}"</c:if>><i class="material-icons">chevron_right</i></a></li>
        </ul>
      </div>
    </div>
  </div>
  </c:if> 

</main>

  <%@include file="/WEB-INF/jspf/footer.jspf" %>
</body>
</html>